language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - yarn install

script:
  - find . -name composer -prune -o -name node_modules -prune -o -name '*.php' -exec php -lf {} \; >/dev/null
  - yarn run php-codesniffer
  - yarn run js-lint

deploy:
  - provider: script
    script: chmod +x ./node_modules/@boldgrid/wordpress-tag-sync/release.sh && ./node_modules/@boldgrid/wordpress-tag-sync/release.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "shrinkwrap_images.zip"
    skip_cleanup: true
    on:
      tags: true
